// node tests/app-icon.mjs — pins the committed icon set to src/app-icon.js.
//
// The icons are generated by `node scripts/build-icons.mjs` and COMMITTED,
// because CI has no browser to rasterise with. That makes them the one part of
// the build that can silently go stale, and this suite is the whole defence.
//
// KNOW THE BOUNDARY OF THE GUARANTEE. Without a rasteriser, nothing here can
// prove a PNG's *pixels* match the current art — only its dimensions, and that
// the SVG it was made from is the one app-icon.js emits today. The sha256 that
// build-icons.mjs stamps into icon.svg is the proxy: change the art without
// rerunning the script and check 2 fails.
//
// Dependency-free, same check()/tally shape as tests/theme-contrast.mjs.

import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { appIconSvg } from "../src/app-icon.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = join(ROOT, "public");
const REGEN = "run `node scripts/build-icons.mjs` and commit public/";

let passed = 0, failed = 0;
const check = (name, fn) => {
  try { fn(); passed++; console.log(`ok    ${name}`); }
  catch (e) { failed++; console.log(`FAIL  ${name}\n      ${e.message}`); }
};

const read = f => readFileSync(join(PUBLIC, f));
const text = f => readFileSync(join(PUBLIC, f), "utf8");

// PNG header by hand: 8-byte signature, then the IHDR chunk (length, type,
// width, height, bit depth, colour type). No dependency, ten lines.
const PNG_SIG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
function ihdr(buf) {
  assert.ok(buf.subarray(0, 8).equals(PNG_SIG), "not a PNG (bad signature)");
  assert.equal(buf.subarray(12, 16).toString("latin1"), "IHDR", "first chunk is not IHDR");
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20), depth: buf[24], colour: buf[25] };
}

/* ---------------- 1. the SVG is the one app-icon.js emits ---------------- */

const svg = text("icon.svg");
const [header, ...rest] = svg.split("\n");
const body = rest.join("\n");

check("public/icon.svg matches appIconSvg('tab')", () => {
  assert.equal(body, appIconSvg("tab"), `public/icon.svg is stale — ${REGEN}`);
});

/* ---------------- 2. the PNGs' source is the one app-icon.js emits ---------------- */

for (const [label, variant] of [["plan", "bleed"], ["crease", "small"]]) {
  check(`icon.svg's stamped ${label} sha256 matches appIconSvg('${variant}')`, () => {
    const m = new RegExp(`${label} sha256:([0-9a-f]{64})`).exec(header);
    assert.ok(m, `icon.svg's generator header has no ${label} hash — ${REGEN}`);
    assert.equal(m[1], createHash("sha256").update(appIconSvg(variant)).digest("hex"),
      `the ${label} rasters were built from different art — ${REGEN}`);
  });
}

/* ---------------- 2b. the two renditions stay separated ---------------- */

check("the small rendition is hidden by a presentation attribute, not by CSS", () => {
  // The order matters. CSS beats presentation attributes, so display="none" in
  // the markup plus `display: block` in the media query means a context that
  // strips <style> falls back to the PLAN. Style it the other way round and
  // that context paints the small glyph on top of the plan instead.
  const tab = appIconSvg("tab");
  assert.match(tab, /<g class="tiny" display="none">/,
    'the .tiny group must carry display="none" inline');
  const block = /@media \(max-width: \d+px\) \{([\s\S]*?)\n\}/.exec(tab);
  assert.ok(block, "the tab variant has no max-width media query");
  assert.match(block[1], /\.tiny \{ display: block \}/,
    "the size media query must be what reveals .tiny");
  assert.match(block[1], /\.plan \{ display: none \}/,
    "the size media query must be what hides .plan");
});

check("appIconSvg('bleed') carries no small rendition", () => {
  // The PNGs are 180px and up, and a PNG cannot evaluate a media query — a
  // .tiny group in there would be an unconditional red tile over the rink.
  const bleed = appIconSvg("bleed");
  assert.ok(!/class="tiny"/.test(bleed), "bleed must be the plan only");
  assert.ok(!/<style>/.test(bleed), "bleed must carry no stylesheet");
});

/* ---------------- 3. no literal colours in the art source ---------------- */

check("src/app-icon.js takes every colour from THEMES", () => {
  const src = readFileSync(join(ROOT, "src", "app-icon.js"), "utf8");
  const bare = src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
  const hex = bare.match(/#[0-9a-fA-F]{3,8}\b/g);
  assert.equal(hex, null, `hardcoded colour(s) ${hex && hex.join(", ")} — read them from THEMES, `
    + "so the icon can't drift from the palette");
  assert.match(bare, /\bTHEMES\b/, "app-icon.js no longer imports THEMES");
});

/* ---------------- 4. the PNGs are the size they claim ---------------- */

const PNGS = [["apple-touch-icon.png", 180], ["icon-192.png", 192], ["icon-512.png", 512]];

for (const [name, px] of PNGS) {
  check(`${name} is ${px}x${px}`, () => {
    const h = ihdr(read(name));
    assert.equal(h.w, px, `width ${h.w}, expected ${px} — ${REGEN}`);
    assert.equal(h.h, px, `height ${h.h}, expected ${px} — ${REGEN}`);
  });
  // A too-eager kill in build-icons.mjs would leave a short but valid-looking
  // file; every real render of this art is comfortably over 2kB.
  check(`${name} is not a truncated write`, () => {
    assert.ok(read(name).length > 2048, `only ${read(name).length} bytes — ${REGEN}`);
  });
}

// iOS composites a transparent apple-touch-icon against BLACK before applying
// its mask, so an alpha channel here means a black ring on the home screen.
check("apple-touch-icon.png has no alpha channel", () => {
  const c = ihdr(read("apple-touch-icon.png")).colour;
  assert.ok(c === 0 || c === 2, `PNG colour type ${c} carries alpha; the bleed variant must be opaque`);
});

/* ---------------- 4b. the iOS Safari fallback ---------------- */

// This whole file exists because iOS Safari does not support SVG favicons: with
// only icon.svg it has no candidate and renders no favicon at all. Parse the
// container rather than just checking it exists — a malformed .ico fails
// silently and looks exactly like the bug it is there to fix.
check("favicon.ico holds the expected raster frames", () => {
  const b = read("favicon.ico");
  assert.equal(b.readUInt16LE(0), 0, "reserved field must be 0");
  assert.equal(b.readUInt16LE(2), 1, "type must be 1 (icon)");
  const n = b.readUInt16LE(4);
  assert.deepEqual(n, 3, `expected 3 frames, got ${n}`);
  const got = [];
  for (let i = 0; i < n; i++) {
    const o = 6 + i * 16;
    const len = b.readUInt32LE(o + 8), off = b.readUInt32LE(o + 12);
    assert.ok(off + len <= b.length, `frame ${i} runs past the end of the file`);
    const frame = b.subarray(off, off + len);
    // PNG payloads inside an .ico are legal (Vista+) and are what we emit, so
    // the IHDR is readable and must agree with the directory entry.
    assert.ok(frame.subarray(0, 8).equals(PNG_SIG), `frame ${i} is not a PNG`);
    const w = frame.readUInt32BE(16), h = frame.readUInt32BE(20);
    assert.equal(b[o], w, `frame ${i}: directory says ${b[o]}px, PNG says ${w}px`);
    assert.equal(w, h, `frame ${i} is not square`);
    got.push(w);
  }
  assert.deepEqual(got, [16, 32, 48], `frame sizes ${got.join("/")}`);
});

/* ---------------- 5. everything referenced actually ships ---------------- */

const html = readFileSync(join(ROOT, "index.html"), "utf8");

check("index.html offers the .ico to Safari and the SVG to everyone else", () => {
  // The SVG needs sizes="any" or Chrome/Firefox may pick the fixed-size .ico
  // over the scalable one, losing the size-responsive rendition entirely.
  assert.match(html, /<link rel="icon" href="favicon\.ico"/,
    "the .ico link is what iOS Safari falls back to — do not remove it");
  assert.match(html, /<link rel="icon" type="image\/svg\+xml" href="icon\.svg" sizes="any"/,
    'the SVG favicon must carry sizes="any" so it is preferred where supported');
});

check("every <link href> in index.html resolves in public/", () => {
  const hrefs = [...html.matchAll(/<link\b[^>]*\bhref="([^"]+)"/g)].map(m => m[1]);
  assert.ok(hrefs.length >= 3, `only ${hrefs.length} <link> tags — the icon set lost one`);
  for (const h of hrefs) {
    if (/^(https?:)?\/\//.test(h)) continue;
    assert.ok(existsSync(join(PUBLIC, h)), `index.html links ${h}, which is not in public/`);
  }
});

const manifest = JSON.parse(text("manifest.webmanifest"));

check("every manifest icon resolves, at the size it declares", () => {
  for (const i of manifest.icons) {
    assert.ok(existsSync(join(PUBLIC, i.src)), `manifest lists ${i.src}, which is not in public/`);
    if (i.sizes === "any") continue;
    const [w, h] = i.sizes.split("x").map(Number);
    const got = ihdr(read(i.src));
    assert.deepEqual([got.w, got.h], [w, h], `${i.src} declares ${i.sizes} but is ${got.w}x${got.h}`);
  }
});

/* ---------------- 6. the invariants the head is carrying ---------------- */

check("index.html still has both theme markers", () => {
  // injectTheme() in vite.config.js throws without these, but it throws at
  // build time — this fails in the suite, which runs first.
  for (const m of ["<!--theme-css-->", "<!--theme-boot-->"])
    assert.ok(html.includes(m), `index.html lost ${m}`);
});

check("manifest declares standalone", () => {
  // browser/minimal-ui would DOWNGRADE an iOS 15.4+ home-screen install that
  // apple-mobile-web-app-capable currently gets right.
  assert.equal(manifest.display, "standalone");
});

check("manifest declares no theme_color", () => {
  // index.html ships two media-scoped theme-color metas so the launch paint is
  // right per scheme with no script. A manifest can only state one, and on some
  // iOS versions it tints the status-bar region that the load-bearing
  // apple-mobile-web-app-status-bar-style comment in index.html is protecting.
  assert.ok(!("theme_color" in manifest),
    "a manifest theme_color overrides the per-scheme metas — see the comment in index.html");
});

check("no icon claims to be maskable", () => {
  // The art has no maskable safe zone; declaring one lets Android crop into
  // the rink instead of letterboxing it.
  for (const i of manifest.icons)
    assert.ok(!/maskable/.test(i.purpose || ""), `${i.src} declares purpose ${i.purpose}`);
});

console.log(`\n${passed + failed} checks: ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
